send_command:
  target:
    entity:
      integration: sony_avr
      domain: media_player
  fields:
    command:
      required: true
      example: home
      selector:
        select:
          custom_value: true
          options:
            - power_toggle
            - volume_up
            - volume_down
            - mute
            - home
            - num0
            - num1
            - num2
            - num3
            - num4
            - num5
            - num6
            - num7
            - num8
            - num9
